#!/bin/sh
export OPENEJB_HOME="$HOME/MWy/OpenEJB"

rm -rf build/classes dist
mkdir -p build/classes/META-INF dist
cp  src/META-INF/persistence.xml build/classes/META-INF/

# server-side beans compilation
javac -cp $OPENEJB_HOME/lib/javaee-api-5.0-1.jar -d build/classes src/**/*.java
jar cvMf dist/ejbsearch.jar -C build/classes .

# client compilation
#javac -cp client.jar *.java
