#!/usr/bin/python

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

TOP = 4*1000*1000

f0 = 0
f1 = 1
S = 0
i = 0
l = 2

while i <= TOP:
    i = f0 + f1
    f0 = f1
    f1 = i
    print i
    
    if (l == 3):
      print '-- adding'
      l = 0
      S = S + i

    l = l + 1

print 'sum =', S
