apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: first-test
spec:
  replicas: 1  # lze změnit: kubectl scale deployment nginx --replicas=4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: 
          IfNotPresent
        securityContext:
          # readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          #runAsNonRoot: true
          #runAsUser: 1000
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /?readiness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /?liveness
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-secret # Název Secretu v Kubernetes
              key: password # Klíč ze Secretu, který obsahuje požadovanou hodnotu
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-test-page
          mountPath: /usr/share/nginx/html/test/index.html
          subPath: index.html
#        - name: nfs-storage
#          mountPath: "/opt/foldermount" # cesta v kontejneru, kam se má úložiště připojit          
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: nginx-test-page
        configMap:
          name: nginx-config
          items:
          - key: index.html
            path: index.html
#      - name: nfs-storage
#        persistentVolumeClaim:
#          claimName: STUDENT927-07 # musí odpovídat názvu vašeho PVC      
      nodeSelector:
        disktype: ssd
      affinity:  # Zde přidáváme sekci pro affinity
        nodeAffinity:  # Specifikace pro node affinity
          requiredDuringSchedulingIgnoredDuringExecution:  # Toto musí být splněno
            nodeSelectorTerms:
            - matchExpressions:  # Výrazy pro shodu s nody
              - key: disktype
                operator: In
                values:
                - ssd
          # preferredDuringSchedulingIgnoredDuringExecution:  # Preferované, ale není to povinné
          # - weight: 1
          #   preference:
          #     matchExpressions:
          #     - key: another-label
          #       operator: In
          #       values:
          #       - another-value      
  